// /////////////////////////////////////////////////////////////////////////////////////
//                           Copyright (c) 2017 - 2017
//                            Coyote Logistics L.L.C.
//                          All Rights Reserved Worldwide
// 
// WARNING:  This program (or document) is unpublished, proprietary
// property of Coyote Logistics L.L.C. and is to be maintained in strict confidence.
// Unauthorized reproduction, distribution or disclosure of this program
// (or document), or any program (or document) derived from it is
// prohibited by State and Federal law, and by local law outside of the U.S.
// /////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices
{

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.datacontract.org/2004/07/WebServices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebServices.Posting.LoadDeleteRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebServices.Posting.LoadListRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebServices.Posting.LoadDeleteByLoadNumberRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebServices.Posting.LoadViewsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebServices.Posting.LoadViewsByLoadNumberRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebServices.Posting.LoadPostingRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IntegrationIdField;
        
        private string PasswordField;
        
        private string UserNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IntegrationId
        {
            get
            {
                return this.IntegrationIdField;
            }
            set
            {
                this.IntegrationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnBase", Namespace="http://schemas.datacontract.org/2004/07/WebServices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebServices.Objects.LoadPostingListReturn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebServices.Objects.LoadViewsReturn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebServices.Objects.LoadPostingReturn))]
    public partial class ReturnBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WebServices.Error[] ErrorsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServices.Error[] Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/WebServices")]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorMessageField;
        
        private string[] SuggestionsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Suggestions
        {
            get
            {
                return this.SuggestionsField;
            }
            set
            {
                this.SuggestionsField = value;
            }
        }
    }
}
namespace WebServices.Posting
{


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadDeleteRequest", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Posting")]
    public partial class LoadDeleteRequest : WebServices.RequestBase
    {
        
        private int[] LoadsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int[] Loads
        {
            get
            {
                return this.LoadsField;
            }
            set
            {
                this.LoadsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadListRequest", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Posting")]
    public partial class LoadListRequest : WebServices.RequestBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadDeleteByLoadNumberRequest", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Posting")]
    public partial class LoadDeleteByLoadNumberRequest : WebServices.RequestBase
    {
        
        private string[] LoadNumbersField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string[] LoadNumbers
        {
            get
            {
                return this.LoadNumbersField;
            }
            set
            {
                this.LoadNumbersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadViewsRequest", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Posting")]
    public partial class LoadViewsRequest : WebServices.RequestBase
    {
        
        private int LoadField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Load
        {
            get
            {
                return this.LoadField;
            }
            set
            {
                this.LoadField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadViewsByLoadNumberRequest", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Posting")]
    public partial class LoadViewsByLoadNumberRequest : WebServices.RequestBase
    {
        
        private string LoadNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LoadNumber
        {
            get
            {
                return this.LoadNumberField;
            }
            set
            {
                this.LoadNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadPostingRequest", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Posting")]
    public partial class LoadPostingRequest : WebServices.RequestBase
    {
        
        private bool FullImportField;
        
        private string HandleField;
        
        private WebServices.Objects.Load[] LoadsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FullImport
        {
            get
            {
                return this.FullImportField;
            }
            set
            {
                this.FullImportField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Handle
        {
            get
            {
                return this.HandleField;
            }
            set
            {
                this.HandleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServices.Objects.Load[] Loads
        {
            get
            {
                return this.LoadsField;
            }
            set
            {
                this.LoadsField = value;
            }
        }
    }
}
namespace WebServices.Objects
{


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Load", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Objects")]
    public partial class Load : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AffiliateField;
        
        private string CreditField;
        
        private System.DateTime DeliveryDateField;
        
        private string DeliveryTimeField;
        
        private string DestinationCityField;
        
        private string DestinationCountryField;
        
        private string DestinationStateField;
        
        private string DistanceField;
        
        private int EquipmentIDField;
        
        private Truckstop2.Objects.TrailerOptionType[] EquipmentOptionsField;
        
        private string FuelPriceField;
        
        private bool IsDailyField;
        
        private bool IsFavoriteField;
        
        private bool IsLoadFullField;
        
        private string LengthField;
        
        private int LoadIdField;
        
        private string LoadNumberField;
        
        private string MileageField;
        
        private string OriginCityField;
        
        private string OriginCountryField;
        
        private string OriginStateField;
        
        private string PaymentAmountField;
        
        private System.DateTime PickUpDateField;
        
        private string PickUpTimeField;
        
        private int QuantityField;
        
        private string SpecInfoField;
        
        private string StopsField;
        
        private string TypeOfEquipmentField;
        
        private string WeightField;
        
        private int WidthField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Affiliate
        {
            get
            {
                return this.AffiliateField;
            }
            set
            {
                this.AffiliateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Credit
        {
            get
            {
                return this.CreditField;
            }
            set
            {
                this.CreditField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime DeliveryDate
        {
            get
            {
                return this.DeliveryDateField;
            }
            set
            {
                this.DeliveryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryTime
        {
            get
            {
                return this.DeliveryTimeField;
            }
            set
            {
                this.DeliveryTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationCity
        {
            get
            {
                return this.DestinationCityField;
            }
            set
            {
                this.DestinationCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationCountry
        {
            get
            {
                return this.DestinationCountryField;
            }
            set
            {
                this.DestinationCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationState
        {
            get
            {
                return this.DestinationStateField;
            }
            set
            {
                this.DestinationStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distance
        {
            get
            {
                return this.DistanceField;
            }
            set
            {
                this.DistanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EquipmentID
        {
            get
            {
                return this.EquipmentIDField;
            }
            set
            {
                this.EquipmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Truckstop2.Objects.TrailerOptionType[] EquipmentOptions
        {
            get
            {
                return this.EquipmentOptionsField;
            }
            set
            {
                this.EquipmentOptionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FuelPrice
        {
            get
            {
                return this.FuelPriceField;
            }
            set
            {
                this.FuelPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDaily
        {
            get
            {
                return this.IsDailyField;
            }
            set
            {
                this.IsDailyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsFavorite
        {
            get
            {
                return this.IsFavoriteField;
            }
            set
            {
                this.IsFavoriteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsLoadFull
        {
            get
            {
                return this.IsLoadFullField;
            }
            set
            {
                this.IsLoadFullField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Length
        {
            get
            {
                return this.LengthField;
            }
            set
            {
                this.LengthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int LoadId
        {
            get
            {
                return this.LoadIdField;
            }
            set
            {
                this.LoadIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoadNumber
        {
            get
            {
                return this.LoadNumberField;
            }
            set
            {
                this.LoadNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mileage
        {
            get
            {
                return this.MileageField;
            }
            set
            {
                this.MileageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginCity
        {
            get
            {
                return this.OriginCityField;
            }
            set
            {
                this.OriginCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginCountry
        {
            get
            {
                return this.OriginCountryField;
            }
            set
            {
                this.OriginCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginState
        {
            get
            {
                return this.OriginStateField;
            }
            set
            {
                this.OriginStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentAmount
        {
            get
            {
                return this.PaymentAmountField;
            }
            set
            {
                this.PaymentAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime PickUpDate
        {
            get
            {
                return this.PickUpDateField;
            }
            set
            {
                this.PickUpDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickUpTime
        {
            get
            {
                return this.PickUpTimeField;
            }
            set
            {
                this.PickUpTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecInfo
        {
            get
            {
                return this.SpecInfoField;
            }
            set
            {
                this.SpecInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stops
        {
            get
            {
                return this.StopsField;
            }
            set
            {
                this.StopsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TypeOfEquipment
        {
            get
            {
                return this.TypeOfEquipmentField;
            }
            set
            {
                this.TypeOfEquipmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Weight
        {
            get
            {
                return this.WeightField;
            }
            set
            {
                this.WeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Width
        {
            get
            {
                return this.WidthField;
            }
            set
            {
                this.WidthField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadPostingListReturn", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Objects")]
    public partial class LoadPostingListReturn : WebServices.ReturnBase
    {
        
        private WebServices.Objects.PostResult[] LoadsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServices.Objects.PostResult[] Loads
        {
            get
            {
                return this.LoadsField;
            }
            set
            {
                this.LoadsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadViewsReturn", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Objects")]
    public partial class LoadViewsReturn : WebServices.ReturnBase
    {
        
        private WebServices.Objects.LoadView[] LoadViewsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServices.Objects.LoadView[] LoadViews
        {
            get
            {
                return this.LoadViewsField;
            }
            set
            {
                this.LoadViewsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadPostingReturn", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Objects")]
    public partial class LoadPostingReturn : WebServices.ReturnBase
    {
        
        private string[] LoadNumbersField;
        
        private int[] LoadsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] LoadNumbers
        {
            get
            {
                return this.LoadNumbersField;
            }
            set
            {
                this.LoadNumbersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Loads
        {
            get
            {
                return this.LoadsField;
            }
            set
            {
                this.LoadsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostResult", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Objects")]
    public partial class PostResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DestinationCityField;
        
        private string DestinationCountryField;
        
        private string DestinationStateField;
        
        private string EquipmentField;
        
        private Truckstop2.Objects.TrailerOptionType[] EquipmentOptionsField;
        
        private Truckstop2.Objects.EquipmentTypes EquipmentTypesField;
        
        private string HandleNameField;
        
        private int IdField;
        
        private bool IsFullField;
        
        private string LoadNumberField;
        
        private int LoadViewCountField;
        
        private string OriginCityField;
        
        private string OriginCountryField;
        
        private string OriginStateField;
        
        private string PaymentField;
        
        private string PickupDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationCity
        {
            get
            {
                return this.DestinationCityField;
            }
            set
            {
                this.DestinationCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationCountry
        {
            get
            {
                return this.DestinationCountryField;
            }
            set
            {
                this.DestinationCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationState
        {
            get
            {
                return this.DestinationStateField;
            }
            set
            {
                this.DestinationStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Equipment
        {
            get
            {
                return this.EquipmentField;
            }
            set
            {
                this.EquipmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Truckstop2.Objects.TrailerOptionType[] EquipmentOptions
        {
            get
            {
                return this.EquipmentOptionsField;
            }
            set
            {
                this.EquipmentOptionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Truckstop2.Objects.EquipmentTypes EquipmentTypes
        {
            get
            {
                return this.EquipmentTypesField;
            }
            set
            {
                this.EquipmentTypesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HandleName
        {
            get
            {
                return this.HandleNameField;
            }
            set
            {
                this.HandleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsFull
        {
            get
            {
                return this.IsFullField;
            }
            set
            {
                this.IsFullField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoadNumber
        {
            get
            {
                return this.LoadNumberField;
            }
            set
            {
                this.LoadNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoadViewCount
        {
            get
            {
                return this.LoadViewCountField;
            }
            set
            {
                this.LoadViewCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginCity
        {
            get
            {
                return this.OriginCityField;
            }
            set
            {
                this.OriginCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginCountry
        {
            get
            {
                return this.OriginCountryField;
            }
            set
            {
                this.OriginCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginState
        {
            get
            {
                return this.OriginStateField;
            }
            set
            {
                this.OriginStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Payment
        {
            get
            {
                return this.PaymentField;
            }
            set
            {
                this.PaymentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickupDate
        {
            get
            {
                return this.PickupDateField;
            }
            set
            {
                this.PickupDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadView", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Objects")]
    public partial class LoadView : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CarrierRatingField;
        
        private string CompanyHomeStateField;
        
        private string CompanyNameField;
        
        private string DispatchNameField;
        
        private string DispatchPhoneField;
        
        private string HandleField;
        
        private bool IsFriendField;
        
        private System.DateTime ViewDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarrierRating
        {
            get
            {
                return this.CarrierRatingField;
            }
            set
            {
                this.CarrierRatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyHomeState
        {
            get
            {
                return this.CompanyHomeStateField;
            }
            set
            {
                this.CompanyHomeStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DispatchName
        {
            get
            {
                return this.DispatchNameField;
            }
            set
            {
                this.DispatchNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DispatchPhone
        {
            get
            {
                return this.DispatchPhoneField;
            }
            set
            {
                this.DispatchPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Handle
        {
            get
            {
                return this.HandleField;
            }
            set
            {
                this.HandleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFriend
        {
            get
            {
                return this.IsFriendField;
            }
            set
            {
                this.IsFriendField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ViewDate
        {
            get
            {
                return this.ViewDateField;
            }
            set
            {
                this.ViewDateField = value;
            }
        }
    }
}
namespace Truckstop2.Objects
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrailerOptionType", Namespace="http://schemas.datacontract.org/2004/07/Truckstop2.Objects")]
    public enum TrailerOptionType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tarps = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hazardous = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PalletExchange = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Team = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Expedited = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EquipmentTypes", Namespace="http://schemas.datacontract.org/2004/07/Truckstop2.Objects")]
    public partial class EquipmentTypes : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CategoryField;
        
        private int CategoryIdField;
        
        private string CodeField;
        
        private string DescriptionField;
        
        private System.Nullable<bool> FullLoadField;
        
        private int IdField;
        
        private bool IsCategorizableField;
        
        private bool IsComboField;
        
        private bool IsTruckPostField;
        
        private int MapToIdField;
        
        private System.Nullable<Truckstop2.Objects.TrailerOptionType> RequiredOptionField;
        
        private bool WebserviceOnlyField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId
        {
            get
            {
                return this.CategoryIdField;
            }
            set
            {
                this.CategoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> FullLoad
        {
            get
            {
                return this.FullLoadField;
            }
            set
            {
                this.FullLoadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCategorizable
        {
            get
            {
                return this.IsCategorizableField;
            }
            set
            {
                this.IsCategorizableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCombo
        {
            get
            {
                return this.IsComboField;
            }
            set
            {
                this.IsComboField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTruckPost
        {
            get
            {
                return this.IsTruckPostField;
            }
            set
            {
                this.IsTruckPostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MapToId
        {
            get
            {
                return this.MapToIdField;
            }
            set
            {
                this.MapToIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Truckstop2.Objects.TrailerOptionType> RequiredOption
        {
            get
            {
                return this.RequiredOptionField;
            }
            set
            {
                this.RequiredOptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WebserviceOnly
        {
            get
            {
                return this.WebserviceOnlyField;
            }
            set
            {
                this.WebserviceOnlyField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.truckstop.com/v11", ConfigurationName="ILoadPosting")]
public interface ILoadPosting
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/PostLoads", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/PostLoadsResponse")]
    WebServices.Objects.LoadPostingReturn PostLoads(WebServices.Posting.LoadPostingRequest loads);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/PostLoads", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/PostLoadsResponse")]
    System.Threading.Tasks.Task<WebServices.Objects.LoadPostingReturn> PostLoadsAsync(WebServices.Posting.LoadPostingRequest loads);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/DeleteLoads", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/DeleteLoadsResponse")]
    WebServices.Objects.LoadPostingReturn DeleteLoads(WebServices.Posting.LoadDeleteRequest loads);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/DeleteLoads", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/DeleteLoadsResponse")]
    System.Threading.Tasks.Task<WebServices.Objects.LoadPostingReturn> DeleteLoadsAsync(WebServices.Posting.LoadDeleteRequest loads);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/GetLoads", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/GetLoadsResponse")]
    WebServices.Objects.LoadPostingListReturn GetLoads(WebServices.Posting.LoadListRequest listRequest);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/GetLoads", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/GetLoadsResponse")]
    System.Threading.Tasks.Task<WebServices.Objects.LoadPostingListReturn> GetLoadsAsync(WebServices.Posting.LoadListRequest listRequest);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/DeleteLoadsByLoadNumber", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/DeleteLoadsByLoadNumberResponse" +
        "")]
    WebServices.Objects.LoadPostingReturn DeleteLoadsByLoadNumber(WebServices.Posting.LoadDeleteByLoadNumberRequest deleteRequest);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/DeleteLoadsByLoadNumber", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/DeleteLoadsByLoadNumberResponse" +
        "")]
    System.Threading.Tasks.Task<WebServices.Objects.LoadPostingReturn> DeleteLoadsByLoadNumberAsync(WebServices.Posting.LoadDeleteByLoadNumberRequest deleteRequest);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/GetLoadViews", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/GetLoadViewsResponse")]
    WebServices.Objects.LoadViewsReturn GetLoadViews(WebServices.Posting.LoadViewsRequest loadNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/GetLoadViews", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/GetLoadViewsResponse")]
    System.Threading.Tasks.Task<WebServices.Objects.LoadViewsReturn> GetLoadViewsAsync(WebServices.Posting.LoadViewsRequest loadNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/GetLoadViewsByLoadNumber", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/GetLoadViewsByLoadNumberRespons" +
        "e")]
    WebServices.Objects.LoadViewsReturn GetLoadViewsByLoadNumber(WebServices.Posting.LoadViewsByLoadNumberRequest loadNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/GetLoadViewsByLoadNumber", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/GetLoadViewsByLoadNumberRespons" +
        "e")]
    System.Threading.Tasks.Task<WebServices.Objects.LoadViewsReturn> GetLoadViewsByLoadNumberAsync(WebServices.Posting.LoadViewsByLoadNumberRequest loadNumber);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ILoadPostingChannel : ILoadPosting, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LoadPostingClient : System.ServiceModel.ClientBase<ILoadPosting>, ILoadPosting
{
    
    public LoadPostingClient()
    {
    }
    
    public LoadPostingClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public LoadPostingClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LoadPostingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LoadPostingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public WebServices.Objects.LoadPostingReturn PostLoads(WebServices.Posting.LoadPostingRequest loads)
    {
        return base.Channel.PostLoads(loads);
    }
    
    public System.Threading.Tasks.Task<WebServices.Objects.LoadPostingReturn> PostLoadsAsync(WebServices.Posting.LoadPostingRequest loads)
    {
        return base.Channel.PostLoadsAsync(loads);
    }
    
    public WebServices.Objects.LoadPostingReturn DeleteLoads(WebServices.Posting.LoadDeleteRequest loads)
    {
        return base.Channel.DeleteLoads(loads);
    }
    
    public System.Threading.Tasks.Task<WebServices.Objects.LoadPostingReturn> DeleteLoadsAsync(WebServices.Posting.LoadDeleteRequest loads)
    {
        return base.Channel.DeleteLoadsAsync(loads);
    }
    
    public WebServices.Objects.LoadPostingListReturn GetLoads(WebServices.Posting.LoadListRequest listRequest)
    {
        return base.Channel.GetLoads(listRequest);
    }
    
    public System.Threading.Tasks.Task<WebServices.Objects.LoadPostingListReturn> GetLoadsAsync(WebServices.Posting.LoadListRequest listRequest)
    {
        return base.Channel.GetLoadsAsync(listRequest);
    }
    
    public WebServices.Objects.LoadPostingReturn DeleteLoadsByLoadNumber(WebServices.Posting.LoadDeleteByLoadNumberRequest deleteRequest)
    {
        return base.Channel.DeleteLoadsByLoadNumber(deleteRequest);
    }
    
    public System.Threading.Tasks.Task<WebServices.Objects.LoadPostingReturn> DeleteLoadsByLoadNumberAsync(WebServices.Posting.LoadDeleteByLoadNumberRequest deleteRequest)
    {
        return base.Channel.DeleteLoadsByLoadNumberAsync(deleteRequest);
    }
    
    public WebServices.Objects.LoadViewsReturn GetLoadViews(WebServices.Posting.LoadViewsRequest loadNumber)
    {
        return base.Channel.GetLoadViews(loadNumber);
    }
    
    public System.Threading.Tasks.Task<WebServices.Objects.LoadViewsReturn> GetLoadViewsAsync(WebServices.Posting.LoadViewsRequest loadNumber)
    {
        return base.Channel.GetLoadViewsAsync(loadNumber);
    }
    
    public WebServices.Objects.LoadViewsReturn GetLoadViewsByLoadNumber(WebServices.Posting.LoadViewsByLoadNumberRequest loadNumber)
    {
        return base.Channel.GetLoadViewsByLoadNumber(loadNumber);
    }
    
    public System.Threading.Tasks.Task<WebServices.Objects.LoadViewsReturn> GetLoadViewsByLoadNumberAsync(WebServices.Posting.LoadViewsByLoadNumberRequest loadNumber)
    {
        return base.Channel.GetLoadViewsByLoadNumberAsync(loadNumber);
    }
}