
CREATE Function GetFirstDayofCurrentWeek()
RETURNS DATETIME

AS

BEGIN

	RETURN CAST(CONVERT(VARCHAR(10), DATEADD(DAY, (DATEPART(DW, GETDATE()) * -1) + 1, GETDATE()), 112) + ' 00:00:00' AS DATETIME)

END

